var modal_language = 'fr'

var home_fr = '<br/><p>Bienvenue sur notre visualisation : Consommation Twitch !</p><p>Le but de ce projet est de visualiser la consommation de streaming sur les 30 streamers considérés comme étant les plus populaires en France. Le classement des streamers est basé sur le classement du site <a target="_blank" href="https://www.twitchmetrics.net/channels/popularity?lang=fr&page=0">twitchmetrics</a> au mois de novembre 2019.</p><p>Pour plus d\'informations sur les éléments de la visualisation ou sur notre équipe, veuillez consulter les onglets Description et About.</p><p>Vous pouvez afficher la version anglaise en cliquant sur le drapeau en haut à droite.</p>'
var home_en = '<br/><p>Welcome on the visualization : Twitch Consumption!</p><p>The goal of this project is to visualize the stream consumption of the 30 streamers considered as the most popular in France. The streamers\' ranking is based on the one from the <a target="_blank" href="https://www.twitchmetrics.net/channels/popularity?lang=fr&page=0">twitchmetrics</a> website as it was in november 2019.</p><p>For more informations about the visualization or our team, please check the Description and About tabs.</p><p>You can display the french version by clicking on the flag on the upper right corner.</p>'

var descr_fr = '<br/><p>Ce projet permet de visualiser la consommation de streaming sur les 30 streamers considérés comme étant les plus populaires en France. Le classement des streamers est basé sur le classement du site <a target="_blank" href="https://www.twitchmetrics.net/channels/popularity?lang=fr&page=0">twitchmetrics</a> au mois de novembre 2019.</p><p>Cette visualisation permet de mettre en évidence 3 patterns différents de streamers :<ul><li>Les streamers ponctuels, ils diffusent du contenu une à deux fois par semaine, ex : <a target="_blank" href="https://www.twitch.tv/squeezielive/">Squeezie</a></li><li>Les streamers réguliers, ils diffusent du contenu quasiment tous les jours, ex : <a target="_blank" href="https://www.twitch.tv/locklear/">Locklear</a></li><li>Les Web TVs, elles sont similaires à des chaînes de télévision. Sur celles-ci des streamers se relaient dans diverses émissions. Le flux de diffusion est alors très peu interrompu sur l’ensemble de la semaine, ex : <a target="_blank" href="https://www.twitch.tv/solary/">Solary</a></li></ul></p><p>La visualisation est composée d’une timeline circulaire et centrale qui affiche les temps de streaming de chacun. On peut y voir apparaître les patterns décrits ci-dessus, afin d’en simplifier la visualisation nous avons organisé les streamers par type. Le fait que cette timeline soit circulaire permet de particulièrement bien mettre en avant les différents types de streamers. Cela permet également de pouvoir visualiser une semaine complète sur un espace restreint, contrairement à une visualisation linéaire.</p><p>La visualisation présente également un area chart annexe, en haut à droite, qui permet de voir le nombre de viewers sur l’ensemble des 30 streamers et pour chacun d’entres-eux.</p><p>Il est possible de sélectionner un streamer en particulier en cliquant sur un de ses arcs sur la timeline ou sur l’aire de son nombre de viewers dans l’area chart. Des informations complémentaires concernant ce streamer s’affichent alors au sein de l\'infobox en bas à droite. On y voit apparaître le nombre d’heures streamées, le nombre de viewers moyens et au maximum, le nombre de streams et un bar-plot du nombre de viewers sur la période sélectionnée.</p><p>En effet, il est possible de sélectionner une période, soit d’une semaine (par défaut), soit d’un jour. Pour sélectionner un jour il faut cliquer sur le jour correspondant sur la timeline principale.</p>'
var descr_en = '<br/><p>This project is a visualization of streaming consumption of the 30 streamers considered as the most populars in France. The ranking of the streamers is based on the one from the <a target="_blank" href="https://www.twitchmetrics.net/channels/popularity?lang=fr&page=0">twitchmetrics</a> website as it was in november 2019.</p><p>This visualization highlights three main types of streamers:<ul><li>Ponctual streamers, they stream once or twice per week, ex : <a target="_blank" href="https://www.twitch.tv/squeezielive/">Squeezie</a></li><li>Regular streamers, they stream almost everyday, ex : <a target="_blank" href="https://www.twitch.tv/locklear/">Locklear</a></li><li>Web TVs, they can be compared to television channels. Streamers take turn in several shows on those channels, the stream is almost never interrupted on the whole week, ex : <a target="_blank" href="https://www.twitch.tv/solary/">Solary</a></li></ul></p><p>The visualization is composed of a central circular timeline which displays the streaming times of each streamer. On that central graph we can see the different types of streamers appear, to simplify the visualization of those types we ordered them by type. The fact that the timeline is circular puts very well in light the different types of streamers. It also allows to easily visualize an entire week in a relatively small space, which would be harder on a linear chart.</p><p>There also is an area chart, in the upper right corner, which displays the number of viewers for each of the 30 streamers.</p><p>It is possible to select a streamer by clicking on one of its arcs on the timeline or on the area of its number of viewers on the area chart. Additional informations on the streamer are then displayed in the infobox on the bottom right corner. We can see the streamed hours number, the average and peak number of viewers, the number of streams and a bar plot with the number of viewers on the selected period.</p><p>Indeed, it is also possible to select a period, it either is of one week (by default) or one day. To select a day, you have to click on the corresponding day on the main timeline.</p>'

var about_fr = '<br/><p>Auteurs :<ul><li>Valentin Comas, <a target="_blank" href="mailto:valentin.comas@etu.univ-lyon1.fr">valentin.comas@etu.univ-lyon1.fr</a></li><li>Thomas Bourg, <a target="_blank" href="mailto:thomas.bourg@etu.univ-lyon1.fr">thomas.bourg@etu.univ-lyon1.fr</a></li><li>Nicolas Désilets, <a target="_blank" href="mailto:nicolas.desilets@etu.univ-lyon1.fr">nicolas.desilets@etu.univ-lyon1.fr</a></li><li>Thomas Ranvier, <a target="_blank" href="mailto:thomas.ranvier@etu.univ-lyon1.fr">thomas.ranvier@etu.univ-lyon1.fr</a></li></ul></p><p>Sources d\'inspirations :<ul><li>Notre inspiration initiale fut <a target="_blank" href="https://medium.com/@hint_fm/design-and-redesign-4ab77206cf9#.3avyf29un">cette visualisation du printemps Arabe</a> sur une timeline circulaire.</li><li>Après plus de recherches nous trouvé <a target="_blank" href="https://datavizproject.com/data-type/radical-histogram/print/">cette visualisation</a> qui nous a également beaucoup inspiré. </li><li>Pour la récolte de nos données, nous avons utilisé <a target="_blank" href="https://dev.twitch.tv/docs/api">l\'API de Twitch</a>.</li><li>Pour le développement de la visualisation nous avons utilisé la <a target="_blank" href="https://github.com/d3/d3/wiki">documentation de d3js</a>.</li></ul></p><p>Cette visualisation a été réalisée dans le cadre du cours de <a target="_blank" href="https://lyondataviz.github.io/teaching/lyon1-m2/2019">data visualization</a> du <a target="_blank" href="http://master-info.univ-lyon1.fr/IA/">M2 Intelligence Artificielle</a> de l\'Université Claude Bernard Lyon 1.</p><p>Pour plus d\'informations n\'hésitez pas à consulter le <a target="_blank" href="https://github.com/ThomasRanvier/twitch_consumption/wiki">wiki</a> du projet.</p>'
var about_en = '<br/><p>Authors:<ul><li>Valentin Comas, <a target="_blank" href="mailto:valentin.comas@etu.univ-lyon1.fr">valentin.comas@etu.univ-lyon1.fr</a></li><li>Thomas Bourg, <a target="_blank" href="mailto:thomas.bourg@etu.univ-lyon1.fr">thomas.bourg@etu.univ-lyon1.fr</a></li><li>Nicolas Désilets, <a target="_blank" href="mailto:nicolas.desilets@etu.univ-lyon1.fr">nicolas.desilets@etu.univ-lyon1.fr</a></li><li>Thomas Ranvier, <a target="_blank" href="mailto:thomas.ranvier@etu.univ-lyon1.fr">thomas.ranvier@etu.univ-lyon1.fr</a></li></ul></p><p>Inspiration sources:<ul><li>Our initial inspiration was <a target="_blank" href="https://medium.com/@hint_fm/design-and-redesign-4ab77206cf9#.3avyf29un">this Arab\' spring visualization</a> on a circular timeline.</li><li>After more research we found <a target="_blank" href="https://datavizproject.com/data-type/radical-histogram/print/">this visualization</a> which inspired us a lot too. </li><li>In order to collect the data we used <a target="_blank" href="https://dev.twitch.tv/docs/api">the Twitch API</a>.</li><li>For the devlopment we used the <a target="_blank" href="https://github.com/d3/d3/wiki">d3js documentation</a>.</li></ul></p><p>This visualization was realized on the <a target="_blank" href="https://lyondataviz.github.io/teaching/lyon1-m2/2019">data visualization course</a> of the Claude Bernard University, Lyon 1, <a target="_blank" href="http://master-info.univ-lyon1.fr/IA/">M2 Intelligence Artificielle</a>.</p><p>For more informations and details do not hesitate to consult the <a target="_blank" href="https://github.com/ThomasRanvier/twitch_consumption/wiki">project wiki</a>.</p>'

document.getElementById('nav-home').innerHTML = home_fr
document.getElementById('nav-descr').innerHTML = descr_fr
document.getElementById('nav-about').innerHTML = about_fr
document.getElementById('nav-home-tab').innerText = 'Accueil'
document.getElementById('nav-descr-tab').innerText = 'Description'
document.getElementById('nav-about-tab').innerText = 'A propos'
document.getElementById('modal-title').innerText = 'Consommation de streaming sur Twitch'

function switch_language() {
    if (modal_language == 'fr') {
        document.getElementById('flag').src = 'https://raw.githubusercontent.com/ThomasRanvier/twitch_consumption/master/data/fr.png'
        document.getElementById('nav-home').innerHTML = home_en
        document.getElementById('nav-descr').innerHTML = descr_en
        document.getElementById('nav-about').innerHTML = about_en
        document.getElementById('nav-home-tab').innerText = 'Home'
        document.getElementById('nav-descr-tab').innerText = 'Description'
        document.getElementById('nav-about-tab').innerText = 'About'
        document.getElementById('modal-title').innerText = 'Streaming consumption on Twitch'
        modal_language = 'en'
    } else {
        document.getElementById('flag').src = 'https://raw.githubusercontent.com/ThomasRanvier/twitch_consumption/master/data/uk.png'
        document.getElementById('nav-home').innerHTML = home_fr
        document.getElementById('nav-descr').innerHTML = descr_fr
        document.getElementById('nav-about').innerHTML = about_fr
        document.getElementById('nav-home-tab').innerText = 'Accueil'
        document.getElementById('nav-descr-tab').innerText = 'Description'
        document.getElementById('nav-about-tab').innerText = 'A propos'
        document.getElementById('modal-title').innerText = 'Consommation de streaming sur Twitch'
        modal_language = 'fr'
    }
}
